(() => {
'use strict';
const $=id=>document.getElementById(id);
const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const fmt=(n,d=2)=>Number(n).toFixed(d);
const state={playing:false,phase:0,last:0,raf:0,logs:[]};
function getNumber(id,fallback){const el=$(id);const n=el?Number(el.value):NaN;return Number.isFinite(n)?n:fallback;}
function params(){const a=getNumber('vizSlit',.6),f=getNumber('vizFreq',600),T=getNumber('vizTemp',20),A=getNumber('vizAmp',.75),timeSpeed=getNumber('vizTimeSpeed',1),incidentMode=$('vizIncidentMode')?.value||'curved',v=331+.6*T,lambda=v/f,ratio=a/lambda,has=ratio>1,theta=has?Math.asin(clamp(lambda/a,0,1)):Math.PI/2,thetaDeg=theta*180/Math.PI;let strength='เด่นมาก';if(ratio>3)strength='น้อย';else if(ratio>1.3)strength='ปานกลาง';else if(ratio>.7)strength='เด่น';return{a,f,T,A,timeSpeed,incidentMode,v,lambda,ratio,has,theta,thetaDeg,strength,showGuides:!!$('vizShowGuides')?.checked};}
function setText(id,text){const el=$(id);if(el)el.textContent=text;}
function labels(p){setText('vizSlitLabel',`${fmt(p.a,2)} m`);setText('vizFreqLabel',`${Math.round(p.f)} Hz`);setText('vizTempLabel',`${Math.round(p.T)} °C`);setText('vizAmpLabel',fmt(p.A,2));setText('vizTimeLabel',`${fmt(p.timeSpeed,1)}×`);setText('vizSpeedLabel',`${fmt(p.v,1)} m/s`);setText('vizLambdaLabel',`${fmt(p.lambda,2)} m`);setText('vizRatioLabel',fmt(p.ratio,2));setText('vizAngleLabel',p.has?`${Math.round(p.thetaDeg)}°`:'แผ่กว้างมาก');setText('vizStrengthLabel',p.strength);setText('vizGuideLabel',p.showGuides?'เปิด':'ปิด');}
function prep(canvas){const rect=canvas.getBoundingClientRect(),cssW=rect.width||canvas.width||1200,cssH=Math.max(280,cssW*(440/1200)),dpr=Math.max(1,Math.min(2.2,window.devicePixelRatio||1));canvas.style.height=`${cssH}px`;if(canvas.width!==Math.round(cssW*dpr)||canvas.height!==Math.round(cssH*dpr)){canvas.width=Math.round(cssW*dpr);canvas.height=Math.round(cssH*dpr);}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w:cssW,h:cssH};}
function play(){if(state.playing)return;state.playing=true;state.last=performance.now();cancelAnimationFrame(state.raf);state.raf=requestAnimationFrame(loop);}
function pause(){state.playing=false;cancelAnimationFrame(state.raf);draw();}
function reset(){state.playing=false;state.phase=0;state.last=0;cancelAnimationFrame(state.raf);draw();}
function loop(now){if(!state.playing)return;const p=params();const dt=state.last?(now-state.last)/1000:0;state.last=now;state.phase+=dt*72*p.timeSpeed;draw();state.raf=requestAnimationFrame(loop);}
function draw(){const c=$('visualizerCanvas');if(!c)return;const p=params();labels(p);const {ctx,w,h}=prep(c);ctx.clearRect(0,0,w,h);background(ctx,w,h);const wallX=w*.45,cy=h*.53,top=h*.15,bottom=h*.85,gap=clamp(p.a*h*.19,16,h*.44),spacing=clamp(p.lambda*96,22,84),phase=((state.phase%spacing)+spacing)%spacing,spread=p.has?p.theta:Math.PI/2;
speaker(ctx,w*.11,cy,p);incoming(ctx,wallX,top,bottom,spacing,phase,p,w,h);wall(ctx,wallX,top,bottom,cy,gap);shadow(ctx,wallX,w,top,bottom,cy,gap);diffract(ctx,wallX,cy,spacing,phase,p,w,h,spread);if(p.showGuides)guides(ctx,wallX,cy,gap,spread,w,h,p);receiver(ctx,w*.90,top,bottom,wallX,cy,p);}
function background(ctx,w,h){const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'#061422');g.addColorStop(.5,'#07111f');g.addColorStop(1,'#050a14');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(148,163,184,.08)';ctx.lineWidth=1;for(let x=0;x<w;x+=42){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=0;y<h;y+=42){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}}
function speaker(ctx,x,y,p){ctx.save();ctx.translate(x,y);ctx.fillStyle='#1e293b';rr(ctx,-36,-24,30,48,10,true,false);ctx.fillStyle='#38bdf8';ctx.beginPath();ctx.moveTo(-6,-17);ctx.lineTo(28,-33);ctx.lineTo(28,33);ctx.lineTo(-6,17);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(224,242,254,.78)';ctx.lineWidth=2;for(let i=1;i<=3;i++){ctx.globalAlpha=.18+p.A*.20;ctx.beginPath();ctx.arc(30,0,12+i*13,-.58,.58);ctx.stroke();}ctx.globalAlpha=1;ctx.fillStyle='#dbeafe';ctx.font='700 11px system-ui,sans-serif';ctx.textAlign='center';ctx.fillText('ลำโพง',-6,49);ctx.restore();}
function incoming(ctx,wallX,top,bottom,spacing,phase,p,w,h){ctx.save();ctx.strokeStyle=`rgba(56,189,248,${.22+p.A*.32})`;ctx.lineWidth=2.2;if(p.incidentMode==='plane'){const offset=((phase%spacing)+spacing)%spacing;for(let x=w*.18+offset;x<wallX-18;x+=spacing){ctx.beginPath();ctx.moveTo(x,top+16);ctx.lineTo(x,bottom-16);ctx.stroke();}}else{const sx=w*.11+26,sy=(top+bottom)/2,maxR=wallX-sx-22;for(let r=phase+spacing*.60;r<maxR;r+=spacing){ctx.beginPath();ctx.arc(sx,sy,r,-.72,.72);ctx.stroke();}}ctx.strokeStyle='rgba(226,232,240,.70)';ctx.fillStyle='rgba(226,232,240,.70)';ctx.lineWidth=2;arrow(ctx,w*.19,top+18,w*.30,top+18);ctx.restore();}
function wall(ctx,x,top,bottom,cy,gap){seg(ctx,x,top,cy-gap/2,24);seg(ctx,x,cy+gap/2,bottom,24);ctx.save();ctx.fillStyle='rgba(226,232,240,.92)';ctx.font='800 12px system-ui,sans-serif';ctx.textAlign='center';ctx.fillText('ช่องเปิดเดี่ยว',x,top-14);ctx.strokeStyle='#facc15';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x+20,cy-gap/2);ctx.lineTo(x+20,cy+gap/2);ctx.stroke();ctx.fillStyle='#fde68a';ctx.font='800 13px system-ui,sans-serif';ctx.textAlign='left';ctx.fillText('a',x+28,cy+5);ctx.restore();}
function seg(ctx,x,y1,y2,ww){const h=y2-y1;if(h<=0)return;const g=ctx.createLinearGradient(x-ww/2,0,x+ww/2,0);g.addColorStop(0,'#1e293b');g.addColorStop(.5,'#64748b');g.addColorStop(1,'#1e293b');ctx.fillStyle=g;rr(ctx,x-ww/2,y1,ww,h,7,true,true);ctx.strokeStyle='rgba(226,232,240,.14)';ctx.stroke();}
function shadow(ctx,wallX,w,top,bottom,cy,gap){ctx.save();ctx.fillStyle='rgba(15,23,42,.18)';ctx.fillRect(wallX+16,top,w-wallX-136,Math.max(0,cy-gap/2-top));ctx.fillRect(wallX+16,cy+gap/2,w-wallX-136,Math.max(0,bottom-cy-gap/2));ctx.restore();}
function diffract(ctx,wallX,cy,spacing,phase,p,w,h,spread){ctx.save();ctx.lineWidth=2.05;const maxR=Math.hypot(w-wallX,h),base=.18+p.A*.28;for(let r=phase+spacing*.55;r<maxR;r+=spacing){const fade=clamp(1-r/(maxR*1.04),.11,1);ctx.strokeStyle=`rgba(45,212,191,${base*fade})`;ctx.beginPath();ctx.arc(wallX,cy,r,-spread,spread);ctx.stroke();}ctx.restore();}
function guides(ctx,wallX,cy,gap,spread,w,h,p){const endX=w*.87,len=endX-wallX,y1=cy-Math.tan(spread)*len,y2=cy+Math.tan(spread)*len;ctx.save();ctx.setLineDash([8,8]);ctx.strokeStyle='rgba(251,113,133,.64)';ctx.lineWidth=1.9;line(ctx,wallX,cy,endX,clamp(y1,8,h-8));line(ctx,wallX,cy,endX,clamp(y2,8,h-8));ctx.setLineDash([]);ctx.fillStyle='rgba(251,113,133,.88)';ctx.font='800 11px system-ui,sans-serif';ctx.fillText(p.has?`θ₁ ≈ ${Math.round(p.thetaDeg)}°`:'แผ่กว้างมาก',wallX+42,cy-14);ctx.restore();}
function receiver(ctx,x,top,bottom,wallX,mid,p){ctx.save();ctx.strokeStyle='rgba(226,232,240,.44)';ctx.lineWidth=2;line(ctx,x,top,x,bottom);ctx.fillStyle='rgba(226,232,240,.82)';ctx.font='700 11px system-ui,sans-serif';ctx.textAlign='center';ctx.fillText('แนวผู้ฟัง',x,bottom+17);ctx.textAlign='left';ctx.fillStyle='rgba(216,180,254,.90)';ctx.fillText('I/I₀',x+12,top-8);const dist=x-wallX;for(let y=top;y<=bottom;y+=3){const th=Math.atan2(y-mid,dist),I=single(th,p.a,p.lambda),alpha=clamp(I*p.A,.04,.92),wid=8+I*28;ctx.fillStyle=`rgba(167,139,250,${alpha})`;rr(ctx,x+7,y-1.15,wid,2.3,2,true,false);}ctx.restore();}
function single(theta,a,lambda){const b=Math.PI*a*Math.sin(theta)/lambda;if(Math.abs(b)<1e-5)return 1;const v=Math.sin(b)/b;return v*v;}
function badge(ctx,w,h,p){ctx.save();const text=p.has?`θ₁≈${Math.round(p.thetaDeg)}°`:'แผ่กว้างมาก';const x=16,y=h-52,bw=Math.min(w-32,400),bh=38;ctx.fillStyle='rgba(2,6,23,.58)';ctx.strokeStyle='rgba(148,163,184,.22)';rr(ctx,x,y,bw,bh,14,true,true);ctx.fillStyle=p.ratio<=1.3?'#86efac':p.ratio<=3?'#fde68a':'#fecaca';ctx.font='800 13px system-ui,sans-serif';ctx.fillText(`λ=${fmt(p.lambda,2)} m   a/λ=${fmt(p.ratio,2)}   ${text}`,x+14,y+24);ctx.restore();}
function line(ctx,x1,y1,x2,y2){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}
function arrow(ctx,x1,y1,x2,y2){const a=Math.atan2(y2-y1,x2-x1);line(ctx,x1,y1,x2,y2);ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-10*Math.cos(a-Math.PI/6),y2-10*Math.sin(a-Math.PI/6));ctx.lineTo(x2-10*Math.cos(a+Math.PI/6),y2-10*Math.sin(a+Math.PI/6));ctx.closePath();ctx.fill();}
function rr(ctx,x,y,w,h,r,fill=true,stroke=false){const q=Math.min(r,Math.abs(w)/2,Math.abs(h)/2);ctx.beginPath();ctx.moveTo(x+q,y);ctx.arcTo(x+w,y,x+w,y+h,q);ctx.arcTo(x+w,y+h,x,y+h,q);ctx.arcTo(x,y+h,x,y,q);ctx.arcTo(x,y,x+w,y,q);ctx.closePath();if(fill)ctx.fill();if(stroke)ctx.stroke();}
function row(){const p=params();return{timestamp:new Date().toISOString(),topic:'Sound Diffraction',incident_wavefront:p.incidentMode,frequency_Hz:Math.round(p.f),temperature_C:Math.round(p.T),speed_m_s:Number(fmt(p.v,2)),wavelength_m:Number(fmt(p.lambda,4)),aperture_a_m:Number(fmt(p.a,3)),aperture_over_lambda:Number(fmt(p.ratio,3)),theta1_deg:p.has?Number(fmt(p.thetaDeg,1)):'',theta1_note:p.has?'first_sound_intensity_minimum_valid':'no_first_minimum_within_0_90_deg',diffraction_strength:p.strength,amplitude_display_A:Number(fmt(p.A,2)),show_guides:p.showGuides};}
function renderLog(){const head=document.querySelector('.localHead'),body=document.querySelector('.localBody');if(!head||!body)return;const sample=state.logs[0]||row(),keys=Object.keys(sample);head.innerHTML=keys.map(k=>`<th>${esc(k)}</th>`).join('');body.innerHTML=state.logs.map(r=>`<tr>${keys.map(k=>`<td>${esc(r[k]??'')}</td>`).join('')}</tr>`).join('');}
function downloadCsv(){if(!state.logs.length)state.logs.push(row());const keys=Object.keys(state.logs[0]),rows=[keys.join(',')].concat(state.logs.map(r=>keys.map(k=>csv(r[k])).join(',')));const blob=new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8;'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`soundDiffraction_${new Date().toISOString().slice(0,19).replace(/[:T]/g,'-')}.csv`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},500);renderLog();}
function savePng(){const c=$('visualizerCanvas');if(!c)return;draw();try{c.toBlob(blob=>{if(!blob)return;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='soundDiffraction.png';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},500);},'image/png');}catch(e){}}
function csv(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;}
function esc(v){return String(v??'').replace(/[&<>\"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]));}
document.addEventListener('DOMContentLoaded',()=>{['vizIncidentMode','vizSlit','vizFreq','vizTemp','vizAmp','vizTimeSpeed','vizShowGuides'].forEach(id=>{$(id)?.addEventListener('input',draw);$(id)?.addEventListener('change',draw);});$('vizPlayBtn')?.addEventListener('click',play);$('vizPauseBtn')?.addEventListener('click',pause);$('vizResetBtn')?.addEventListener('click',reset);$('vizExportBtn')?.addEventListener('click',savePng);document.querySelector('.localCaptureBtn')?.addEventListener('click',()=>{state.logs.push(row());renderLog();});document.querySelector('.localDownloadBtn')?.addEventListener('click',downloadCsv);document.querySelector('.localClearBtn')?.addEventListener('click',()=>{state.logs=[];renderLog();});draw();renderLog();});
})();